Update version checking workflow
openshift-helm-charts/development pull request #131
Opened 2022-05-25 18:01 UTC by mmulholla

Made quite a few changes:

- Fixed the flows so they actually work.
- Issues are only opened if a chart has a failure.
   - In the issues dperaza and mmulholla are tagged not the chart owners.
   - The issue should then be reviewed to ensure it is correct before tagging the owners.
- Updated the content of any issues opened.
- Issues are also opened for a dry run but in openshift-helm-charts/sandbox, the issue titles start "Dry run:"
- Dry run will run the checks whether or not version changes are detected.
- Dry run will work from a fork.
- Added a bunch of logging for easier diagnosis of failures.
- Testing hit some issues with the secondary api rate limit from github which happens when a workflow is creating github content too quickly. To resolve this I added a couple of 5 second sleeps which fixed the issue for each chart tested (note: 3 seconds sleeps did not fix the issue).
- Re-enabled the cron job now the flows work.
- renamed the workflow yaml file to be more descriptive
   - was schedule.yaml, now check_version.yaml

Testing:

- Have tested extensively - you can see a clean dry-run here: https://github.com/mmulholla/development/actions/runs/2386105542
- Dry run opens issue in sandbox - you can see a sample here: https://github.com/openshift-helm-charts/sandbox/issues/21423

2022-05-31 11:38 UTC, isutton requested changes
There are some minors, other than that LGTM.

2022-05-31 21:22 UTC, mmulholla commented on tests/functional/utils/notifier.py
> +        else:
Thx, it was left over after my last change, left it in to do a test and did not go back to remove it.

2022-05-31 21:22 UTC, mmulholla commented on .github/workflows/version_check.yml
> +          pwd
removed it.

2022-06-01 08:48 UTC, isutton approved these changes
LGTM.

2022-06-01 11:34 UTC, merged