Release changes for stage repo
openshift-helm-charts/development pull request #171
Opened 2022-10-26 10:43 UTC by tisutisu

This PR is part of the work for story: https://issues.redhat.com/browse/HELM-395

2022-10-31 12:31 UTC, mmulholla requested changes

2022-11-03 09:49 UTC, tisutisu commented on release/release_info.json
> +  "stage" : {
As discussed, changed the approach now in the latest commit ca1a440

2022-11-03 09:51 UTC, tisutisu commented on scripts/src/release/releaser.py
> +        repository = "stage"
With the changed approach in commit ca1a440 there will be two repository now one is from_repository and another is to_repository

2022-11-16 22:21 UTC, mmulholla approved these changes
LGTM

2022-11-17 08:05 UTC, merged