Added change to send notification based on job status
openshift-helm-charts/development pull request #204
Opened 2023-01-16 08:10 UTC by tisutisu

This PR will address story https://issues.redhat.com/browse/HELM-444 
Also added change to stop CodeQL analysis job to run on forked repos.

2023-01-17 15:01 UTC, mmulholla requested changes
A couple of minor comments.

2023-01-18 06:16 UTC, tisutisu commented on .github/workflows/version_check.yml
>            SOFTWARE_VERSION: ${{ steps.get_curr_cv_version.outputs.current_cv_digest }}
Removed the env variables as they are not needed in the latest commit

2023-01-18 06:16 UTC, tisutisu commented on .github/workflows/version_check.yml
> +          SOFTWARE_VERSION: ${{ steps.get_curr_cv_version.outputs.current_cv_digest }}
Removed the env variables as they are not needed in the latest commit

2023-01-18 13:35 UTC, mmulholla approved these changes
LGTM

2023-01-18 13:41 UTC, merged