Implement bugfix for chart dependencies and gitops.
openshift-helm-charts/development pull request #331
Opened 2024-03-04 22:00 UTC by komish

# Do Not Merge.

I will remove :point_up: if and when this this is valid to merge/review. I have intentionally not applied the *draft* label because this prevents certain CI operations from running.

---

This PR contains all of the impactful changes to how the certification pipeline works in order to resolve issues when depending on charts we provide.

In effect, this PR enables:

- Locked helm chart name tracking and generation
- Checks on OWNERS file submission to ensure locks are respected
- Fixes indexing strategy to index on chart names only

In addition, this PR includes E2E testing extensions for some of the new logic.

---
Change summary by file:

.github/workflows/mercury_bot.yml
- Only run this on changes to partner OWNERS files.
- Make sure that the incoming content is valid.
- Make sure the incoming chart name is not locked.

scripts/src/checkprcontent/checkpr.py
- Make sure we're adding the chart name to the github output.
- Ensure redhat charts follow proper standards at chart content check time. This is a secondary check to the one that's executed at OWNERS file submission time via GHA.
- Ensure the index key is set to the chart's name (changed from `org-chart`).

tests/functional/behave_features/common/utils/chart_certification.py
- Ensure the index key is set to the chart's name (changed from `org-chart`).

tests/functional/behave_features/environment.py
- Defines the OWNERS file testing fixture
- Adds the fixture to the scenario when the proper references are added in the scenario tests

.github/workflows/owners-redhat.yml (new)
- On Red Hat OWNERS file submissions, will check to make sure that the content matches standards.

.github/workflows/lock-sanity-check.yml (new)
- Sanity checks chart lock workflows by running on every main push, and notifying on failures.

.github/workflows/check-locks-on-owners-submission.yml (new)
- Ensures new redhat/community owners files do not encroach on locks.

tests/functional/behave_features/HC-20_owners_file.feature (new)
- Defines the new Helm Cert E2E test for OWNERS files,

tests/functional/behave_features/steps/implementation_owners.py (new)
- Implements the new Helm Cert E2E test for OWNERS files.

2024-03-12 11:17 UTC, mgoerens requested changes
Only blocking issue for me is the question of whether we also enforce the `redhat-` prefix on community/redhat charts. Otherwise minor comments.

Reg. action versions, there are multiple occurrences of slightly outdated actions, so if you want to fix them all at once (not optimized):
```
ACTION_NAME="actions/checkout"; grep "$ACTION_NAME" -rnl .github/ | xargs sed -i "s:$ACTION_NAME@v3:$ACTION_NAME@v4:g"
ACTION_NAME="actions/github-script"; grep "$ACTION_NAME" -rnl .github/ | xargs sed -i "s:$ACTION_NAME@v6:$ACTION_NAME@v7:g"
ACTION_NAME="actions/setup-python"; grep "$ACTION_NAME" -rnl .github/ | xargs sed -i "s:$ACTION_NAME@v4:$ACTION_NAME@v5:g"
```

Finally a general comment regarding newlines between steps. Sometimes there aren't (e.g. .github/workflows/owners-redhat.yml), sometimes there are. I feel it's more readable with newlines, but you might have a different opinion ?

2024-03-12 11:17 UTC, mgoerens commented on scripts/src/checkprcontent/checkpr.py
> +            sys.exit(1)
We are also enforcing charts under community/redhat to have this prefix, correct ?Seeing the conditions under which we run the .github/workflows/owners-redhat.yml workflow:
```
on:
  pull_request:
    paths:
    - charts/redhat/**/OWNERS
    - charts/community/redhat/**/OWNERS
```

If yes, this is going to fail here.

2024-03-12 13:49 UTC, jsm84 commented on scripts/src/checkprcontent/checkpr.py
> +            sys.exit(1)
@mgoerens we are only enforcing Red hat provided charts to have the `redhat-` prefix, while the `<vendor>-` prefix is being dropped for community and partner charts.

The reason was we didn't want Red Hat "squatting" on chart names for a community project or a partner's product (the latter case is much less likely).

2024-03-15 18:07 UTC, komish commented on .github/workflows/check-locks-on-owners-submission.yml
> +    runs-on: ubuntu-20.04
I think making it a conscious bump avoids surprises. That said, I see both 22.04 and 20.04 being used throughout (other than latest). For the files I'm modifying/updating, I'll explicitly use 22.04 and we can update any 20.04's to 22.04 in a future patch.

2024-03-15 18:14 UTC, komish commented on .github/workflows/lock-sanity-check.yml
> +          cc @komish
Eventually, I'd like to cc a group, but we're not there yet.

2024-03-15 20:18 UTC, komish commented on .github/workflows/check-locks-on-owners-submission.yml
> +      - name: get files changed
Agreed - I think your work on the precheck idea would be perfect to reuse here. I think when that's ready and merged in, we can rework this piece here to use it and standardize into one place.

With that in mind, I'm not seeing an action to take today. I'll let you mark this as resolved if you agree.

2024-03-15 20:52 UTC, komish commented on .github/workflows/check-locks-on-owners-submission.yml
> +          test "${owner_contents_vendor_label}" = "${{ steps.gather-metadata.outputs.organization }}"
On one hand, I hesitate to add too many commenting "branches" to the workflow(s). On the other, I much prefer the branches to some of the abstractions we have, whereby any task can include data to be added to the PR as a comment, and they're all concatenated.

With that in mind, I've added a comment step for this step.

2024-03-15 21:00 UTC, komish commented on scripts/src/checkprcontent/checkpr.py
> +            sys.exit(1)
This is one of the earliest modifications I made, so please cross-check me intently! 

These code changes in checkpr check the **organization**, but not the **category**. That is, a chart that resides in `charts/redhat/redhat/myapp` has a category of redhat, an organization of redhat, and a chartname of myapp. 

A chart residing in `charts/community/redhat/anotherapp` has a category of community, an organization of redhat, and a chartname of anotherapp. 

The highlighted code snippet checks for **organization** values that are not redhat, and prevents them from using the prefix. Equally the workflow you mentioned (and earlier in checkpr) double checks to make sure submitted charts comply with the requirement to have the redhat prefix.

With that in mind, I believe the checkpr code is valid as written - but as mentioned, it's one of the earlier code snippets I wrote in the PoC, so please triple check me.

2024-03-15 21:10 UTC, komish commented
@mgoerens I believe I've addressed everything you've requested.

Re: Newlines between steps. I've received that feedback before. I don't find it strictly necessary, but I also don't mind it at all. If I've missed them, I'm happy to add them. If it doesn't happen in this PR, I can go back and normalize all workflows at the same time that I'm standardizing on a single github runner image (e.g. the ubuntu-22.04 change).

2024-03-18 11:06 UTC, mgoerens commented on scripts/src/checkprcontent/checkpr.py
> +            sys.exit(1)
> These code changes in checkpr check the organization, but not the category

I overlooked that. Thanks, that answers it then.

2024-03-18 11:06 UTC, mgoerens commented on .github/workflows/check-locks-on-owners-submission.yml
> +        uses: actions/checkout@v3
I still see `v3` here ? Again, nothing major, happy to take this point outside of this PR if we want to move fast.

2024-03-18 11:11 UTC, mgoerens approved these changes

2024-03-18 18:53 UTC, merged